package ec.edu.ups.biblioteca.views;

import ec.edu.ups.biblioteca.controllers.AutorController;
import ec.edu.ups.biblioteca.models.Autor;
import ec.edu.ups.biblioteca.utils.Idioma;
import ec.edu.ups.biblioteca.utils.Idiomatizable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class AutorView extends javax.swing.JInternalFrame implements Idiomatizable{

    /**
     * Creates new form AutorView
     */
    
    public AutorView() {
        initComponents();
    }

    public void limpiarCampos() {
        txtCodigoAutor.setText("");
        txtNombre.setText("");
        txtNacionalidad.setText("");
        txtFechaNac.setText("");
    }
    
    @Override
    public void aplicarIdioma() {
        java.util.ResourceBundle bundle = Idioma.getBundle();

        jLabel1.setText(bundle.getString("autor.lbl.pregunta"));
        jLabel2.setText(bundle.getString("autor.lbl.camposInfo"));
        jLabel3.setText(bundle.getString("autor.lbl.codigo"));
        jLabel4.setText(bundle.getString("autor.lbl.nombre"));
        jLabel5.setText(bundle.getString("autor.lbl.nacionalidad"));
        jLabel6.setText(bundle.getString("autor.lbl.fechaNacimiento"));

        btnCrearAutor.setText(bundle.getString("autor.btn.crear"));
        btnBuscarAutor.setText(bundle.getString("autor.btn.buscar"));
        btnActualizarAutor.setText(bundle.getString("autor.btn.actualizar"));
        btnEliminarAutor.setText(bundle.getString("autor.btn.eliminar"));
        btnListarAutor.setText(bundle.getString("autor.btn.listar"));
        btnLimpiarCampos.setText(bundle.getString("autor.btn.limpiar"));

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaDeAutores.getModel();
        modelo.setColumnIdentifiers(new Object[]{
            bundle.getString("autor.col.codigo"),
            bundle.getString("autor.col.nombre"),
            bundle.getString("autor.col.nacionalidad"),
            bundle.getString("autor.col.fechaNacimiento")
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCrearAutor = new javax.swing.JButton();
        btnBuscarAutor = new javax.swing.JButton();
        btnActualizarAutor = new javax.swing.JButton();
        btnEliminarAutor = new javax.swing.JButton();
        btnListarAutor = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoAutor = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeAutores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro del Autor - Vista");

        jPanel1.setBackground(new java.awt.Color(114, 114, 82));

        jLabel1.setText("Seleccione primero la acción que necesita realizar:");

        btnCrearAutor.setText("Crear");
        btnCrearAutor.addActionListener(this::btnCrearAutorActionPerformed);

        btnBuscarAutor.setText("Buscar");
        btnBuscarAutor.addActionListener(this::btnBuscarAutorActionPerformed);

        btnActualizarAutor.setText("Actualizar");
        btnActualizarAutor.addActionListener(this::btnActualizarAutorActionPerformed);

        btnEliminarAutor.setText("Eliminar");
        btnEliminarAutor.addActionListener(this::btnEliminarAutorActionPerformed);

        btnListarAutor.setText("Listar");
        btnListarAutor.addActionListener(this::btnListarAutorActionPerformed);

        btnLimpiarCampos.setText("Limpiar");
        btnLimpiarCampos.addActionListener(this::btnLimpiarCamposActionPerformed);

        jLabel2.setText("Los textos se habilitarán según la acción seleccionada:");

        jLabel3.setText("Código del Autor:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Nacionalidad:");

        jLabel6.setText("Fecha de Nacimiento:");

        txtCodigoAutor.setText("0");
        txtCodigoAutor.addActionListener(this::txtCodigoAutorActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtNacionalidad.addActionListener(this::txtNacionalidadActionPerformed);

        txtFechaNac.setText("AAAA-MM-DD");
        txtFechaNac.addActionListener(this::txtFechaNacActionPerformed);

        tablaDeAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre:", "Nacionalidad", "Fecha de Nacimiento:"
            }
        ));
        jScrollPane1.setViewportView(tablaDeAutores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(718, Short.MAX_VALUE)
                .addComponent(btnLimpiarCampos)
                .addGap(239, 239, 239))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnActualizarAutor)
                                        .addGap(138, 138, 138))
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33)
                                .addComponent(btnListarAutor))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEliminarAutor)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCrearAutor)
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarAutor)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel6))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarAutor)
                    .addComponent(btnActualizarAutor)
                    .addComponent(btnCrearAutor)
                    .addComponent(btnListarAutor)
                    .addComponent(btnEliminarAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(48, 48, 48)
                .addComponent(btnLimpiarCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jLabel1.getAccessibleContext().setAccessibleName("AutorView");
        btnCrearAutor.getAccessibleContext().setAccessibleName("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Registro del Autor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAutorActionPerformed

    }//GEN-LAST:event_btnCrearAutorActionPerformed

    private void btnBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAutorActionPerformed
                
    }//GEN-LAST:event_btnBuscarAutorActionPerformed

    private void btnActualizarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAutorActionPerformed
        
    }//GEN-LAST:event_btnActualizarAutorActionPerformed

    private void btnEliminarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAutorActionPerformed
        
    }//GEN-LAST:event_btnEliminarAutorActionPerformed

    private void btnListarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarAutorActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void txtCodigoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAutorActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadActionPerformed

    private void txtFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacActionPerformed
    
    public void mostrarAutorEnCampos(Autor autor) {
        txtNombre.setText(autor.getNombre());
        txtNacionalidad.setText(autor.getNacionalidad());
        txtFechaNac.setText(autor.getFechadeNac().toString());
    }
    
    public void actualizarTabla(List<Autor> autores){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nacionalidad");
        modelo.addColumn("Fecha de Nacimiento");
        
        for (Autor autor : autores) {
            Object[] fila = {autor.getCodigoAutor(), 
                autor.getNombre(), autor.getNacionalidad(), 
                autor.getFechadeNac().toString()};
            modelo.addRow(fila);
        }
        tablaDeAutores.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAutor;
    private javax.swing.JButton btnBuscarAutor;
    private javax.swing.JButton btnCrearAutor;
    private javax.swing.JButton btnEliminarAutor;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnListarAutor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDeAutores;
    private javax.swing.JTextField txtCodigoAutor;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    public JButton getBtnActualizarAutor() {
        return btnActualizarAutor;
    }

    public JButton getBtnBuscarAutor() {
        return btnBuscarAutor;
    }

    public JButton getBtnCrearAutor() {
        return btnCrearAutor;
    }

    public JButton getBtnEliminarAutor() {
        return btnEliminarAutor;
    }

    public JButton getBtnLimpiarCampos() {
        return btnLimpiarCampos;
    }

    public JButton getBtnListarAutor() {
        return btnListarAutor;
    }

    public JTextField getTxtCodigoAutor() {
        return txtCodigoAutor;
    }

    public JTextField getTxtFechaNac() {
        return txtFechaNac;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidad;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }


}
